### ISSUE TITLE
Can't install inside of lxplus

### ISSUE THREAD

**Issue by kdona** [AlbertoPdRF/root-file-viewer#14] opened 2022-04-05 21:10 UTC
Hello! I am having issues using root-file-viewer inside of lxplus. I have a version downloaded onto my copy of vscode but on lxplus I see the extension is missing as-
This extension is disabled in this workspace because it is defined to run in the Remote Extension Host. Please install the extension in 'SSH: lxplus.cern.ch' to enable.

Then attempting to "install in SSH: lxplus.cern.ch" results in my ssh connection closing and no luck with the install. This doesn't happen with other extensions so it doesn't seem to be an lxplus issue.

**Comment by AlbertoPdRF** [comment] 2022-08-11 13:01
I'm closing this issue now, as I think that the problem might have been caused by the extension having so many files and taking so long to install before, which has been fixed since `v0.7.0`.

**Closed by AlbertoPdRF** 2022-08-11 13:01 UTC
Labels: bug
